<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'code3' => 'AFG', 'numeric_code' => '004', 'capital' => 'Kabul', 'flag_emoji' => '🇦🇫', 'is_active' => true],
            ['name' => 'Albania', 'code' => 'AL', 'code3' => 'ALB', 'numeric_code' => '008', 'capital' => 'Tirana', 'flag_emoji' => '🇦🇱', 'is_active' => true],
            ['name' => 'Algeria', 'code' => 'DZ', 'code3' => 'DZA', 'numeric_code' => '012', 'capital' => 'Algiers', 'flag_emoji' => '🇩🇿', 'is_active' => true],
            ['name' => 'Andorra', 'code' => 'AD', 'code3' => 'AND', 'numeric_code' => '020', 'capital' => 'Andorra la Vella', 'flag_emoji' => '🇦🇩', 'is_active' => true],
            ['name' => 'Angola', 'code' => 'AO', 'code3' => 'AGO', 'numeric_code' => '024', 'capital' => 'Luanda', 'flag_emoji' => '🇦🇴', 'is_active' => true],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'code3' => 'ATG', 'numeric_code' => '028', 'capital' => "Saint John's", 'flag_emoji' => '🇦🇬', 'is_active' => true],
            ['name' => 'Argentina', 'code' => 'AR', 'code3' => 'ARG', 'numeric_code' => '032', 'capital' => 'Buenos Aires', 'flag_emoji' => '🇦🇷', 'is_active' => true],
            ['name' => 'Armenia', 'code' => 'AM', 'code3' => 'ARM', 'numeric_code' => '051', 'capital' => 'Yerevan', 'flag_emoji' => '🇦🇲', 'is_active' => true],
            ['name' => 'Australia', 'code' => 'AU', 'code3' => 'AUS', 'numeric_code' => '036', 'capital' => 'Canberra', 'flag_emoji' => '🇦🇺', 'is_active' => true],
            ['name' => 'Austria', 'code' => 'AT', 'code3' => 'AUT', 'numeric_code' => '040', 'capital' => 'Vienna', 'flag_emoji' => '🇦🇹', 'is_active' => true],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'code3' => 'AZE', 'numeric_code' => '031', 'capital' => 'Baku', 'flag_emoji' => '🇦🇿', 'is_active' => true],
            ['name' => 'Bahamas', 'code' => 'BS', 'code3' => 'BHS', 'numeric_code' => '044', 'capital' => 'Nassau', 'flag_emoji' => '🇧🇸', 'is_active' => true],
            ['name' => 'Bahrain', 'code' => 'BH', 'code3' => 'BHR', 'numeric_code' => '048', 'capital' => 'Manama', 'flag_emoji' => '🇧🇭', 'is_active' => true],
            ['name' => 'Bangladesh', 'code' => 'BD', 'code3' => 'BGD', 'numeric_code' => '050', 'capital' => 'Dhaka', 'flag_emoji' => '🇧🇩', 'is_active' => true],
            ['name' => 'Barbados', 'code' => 'BB', 'code3' => 'BRB', 'numeric_code' => '052', 'capital' => 'Bridgetown', 'flag_emoji' => '🇧🇧', 'is_active' => true],
            ['name' => 'Belarus', 'code' => 'BY', 'code3' => 'BLR', 'numeric_code' => '112', 'capital' => 'Minsk', 'flag_emoji' => '🇧🇾', 'is_active' => true],
            ['name' => 'Belgium', 'code' => 'BE', 'code3' => 'BEL', 'numeric_code' => '056', 'capital' => 'Brussels', 'flag_emoji' => '🇧🇪', 'is_active' => true],
            ['name' => 'Belize', 'code' => 'BZ', 'code3' => 'BLZ', 'numeric_code' => '084', 'capital' => 'Belmopan', 'flag_emoji' => '🇧🇿', 'is_active' => true],
            ['name' => 'Benin', 'code' => 'BJ', 'code3' => 'BEN', 'numeric_code' => '204', 'capital' => 'Porto-Novo', 'flag_emoji' => '🇧🇯', 'is_active' => true],
            ['name' => 'Bhutan', 'code' => 'BT', 'code3' => 'BTN', 'numeric_code' => '064', 'capital' => 'Thimphu', 'flag_emoji' => '🇧🇹', 'is_active' => true],
            ['name' => 'Bolivia', 'code' => 'BO', 'code3' => 'BOL', 'numeric_code' => '068', 'capital' => 'Sucre', 'flag_emoji' => '🇧🇴', 'is_active' => true],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'code3' => 'BIH', 'numeric_code' => '070', 'capital' => 'Sarajevo', 'flag_emoji' => '🇧🇦', 'is_active' => true],
            ['name' => 'Botswana', 'code' => 'BW', 'code3' => 'BWA', 'numeric_code' => '072', 'capital' => 'Gaborone', 'flag_emoji' => '🇧🇼', 'is_active' => true],
            ['name' => 'Brazil', 'code' => 'BR', 'code3' => 'BRA', 'numeric_code' => '076', 'capital' => 'Brasília', 'flag_emoji' => '🇧🇷', 'is_active' => true],
            ['name' => 'Brunei', 'code' => 'BN', 'code3' => 'BRN', 'numeric_code' => '096', 'capital' => 'Bandar Seri Begawan', 'flag_emoji' => '🇧🇳', 'is_active' => true],
            ['name' => 'Bulgaria', 'code' => 'BG', 'code3' => 'BGR', 'numeric_code' => '100', 'capital' => 'Sofia', 'flag_emoji' => '🇧🇬', 'is_active' => true],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'code3' => 'BFA', 'numeric_code' => '854', 'capital' => 'Ouagadougou', 'flag_emoji' => '🇧🇫', 'is_active' => true],
            ['name' => 'Burundi', 'code' => 'BI', 'code3' => 'BDI', 'numeric_code' => '108', 'capital' => 'Gitega', 'flag_emoji' => '🇧🇮', 'is_active' => true],
            ['name' => 'Cambodia', 'code' => 'KH', 'code3' => 'KHM', 'numeric_code' => '116', 'capital' => 'Phnom Penh', 'flag_emoji' => '🇰🇭', 'is_active' => true],
            ['name' => 'Cameroon', 'code' => 'CM', 'code3' => 'CMR', 'numeric_code' => '120', 'capital' => 'Yaoundé', 'flag_emoji' => '🇨🇲', 'is_active' => true],
            ['name' => 'Canada', 'code' => 'CA', 'code3' => 'CAN', 'numeric_code' => '124', 'capital' => 'Ottawa', 'flag_emoji' => '🇨🇦', 'is_active' => true],
            ['name' => 'Cape Verde', 'code' => 'CV', 'code3' => 'CPV', 'numeric_code' => '132', 'capital' => 'Praia', 'flag_emoji' => '🇨🇻', 'is_active' => true],
            ['name' => 'Central African Republic', 'code' => 'CF', 'code3' => 'CAF', 'numeric_code' => '140', 'capital' => 'Bangui', 'flag_emoji' => '🇨🇫', 'is_active' => true],
            ['name' => 'Chad', 'code' => 'TD', 'code3' => 'TCD', 'numeric_code' => '148', 'capital' => "N'Djamena", 'flag_emoji' => '🇹🇩', 'is_active' => true],
            ['name' => 'Chile', 'code' => 'CL', 'code3' => 'CHL', 'numeric_code' => '152', 'capital' => 'Santiago', 'flag_emoji' => '🇨🇱', 'is_active' => true],
            ['name' => 'China', 'code' => 'CN', 'code3' => 'CHN', 'numeric_code' => '156', 'capital' => 'Beijing', 'flag_emoji' => '🇨🇳', 'is_active' => true],
            ['name' => 'Colombia', 'code' => 'CO', 'code3' => 'COL', 'numeric_code' => '170', 'capital' => 'Bogotá', 'flag_emoji' => '🇨🇴', 'is_active' => true],
            ['name' => 'Comoros', 'code' => 'KM', 'code3' => 'COM', 'numeric_code' => '174', 'capital' => 'Moroni', 'flag_emoji' => '🇰🇲', 'is_active' => true],
            ['name' => 'Congo (Brazzaville)', 'code' => 'CG', 'code3' => 'COG', 'numeric_code' => '178', 'capital' => 'Brazzaville', 'flag_emoji' => '🇨🇬', 'is_active' => true],
            ['name' => 'Congo (Kinshasa)', 'code' => 'CD', 'code3' => 'COD', 'numeric_code' => '180', 'capital' => 'Kinshasa', 'flag_emoji' => '🇨🇩', 'is_active' => true],
            ['name' => 'Costa Rica', 'code' => 'CR', 'code3' => 'CRI', 'numeric_code' => '188', 'capital' => 'San José', 'flag_emoji' => '🇨🇷', 'is_active' => true],
            ['name' => 'Croatia', 'code' => 'HR', 'code3' => 'HRV', 'numeric_code' => '191', 'capital' => 'Zagreb', 'flag_emoji' => '🇭🇷', 'is_active' => true],
            ['name' => 'Cuba', 'code' => 'CU', 'code3' => 'CUB', 'numeric_code' => '192', 'capital' => 'Havana', 'flag_emoji' => '🇨🇺', 'is_active' => true],
            ['name' => 'Cyprus', 'code' => 'CY', 'code3' => 'CYP', 'numeric_code' => '196', 'capital' => 'Nicosia', 'flag_emoji' => '🇨🇾', 'is_active' => true],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'code3' => 'CZE', 'numeric_code' => '203', 'capital' => 'Prague', 'flag_emoji' => '🇨🇿', 'is_active' => true],
            ['name' => 'Denmark', 'code' => 'DK', 'code3' => 'DNK', 'numeric_code' => '208', 'capital' => 'Copenhagen', 'flag_emoji' => '🇩🇰', 'is_active' => true],
            ['name' => 'Djibouti', 'code' => 'DJ', 'code3' => 'DJI', 'numeric_code' => '262', 'capital' => 'Djibouti', 'flag_emoji' => '🇩🇯', 'is_active' => true],
            ['name' => 'Dominica', 'code' => 'DM', 'code3' => 'DMA', 'numeric_code' => '212', 'capital' => 'Roseau', 'flag_emoji' => '🇩🇲', 'is_active' => true],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'code3' => 'DOM', 'numeric_code' => '214', 'capital' => 'Santo Domingo', 'flag_emoji' => '🇩🇴', 'is_active' => true],
            ['name' => 'Ecuador', 'code' => 'EC', 'code3' => 'ECU', 'numeric_code' => '218', 'capital' => 'Quito', 'flag_emoji' => '🇪🇨', 'is_active' => true],
            ['name' => 'Egypt', 'code' => 'EG', 'code3' => 'EGY', 'numeric_code' => '818', 'capital' => 'Cairo', 'flag_emoji' => '🇪🇬', 'is_active' => true],
            ['name' => 'El Salvador', 'code' => 'SV', 'code3' => 'SLV', 'numeric_code' => '222', 'capital' => 'San Salvador', 'flag_emoji' => '🇸🇻', 'is_active' => true],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'code3' => 'GNQ', 'numeric_code' => '226', 'capital' => 'Malabo', 'flag_emoji' => '🇬🇶', 'is_active' => true],
            ['name' => 'Eritrea', 'code' => 'ER', 'code3' => 'ERI', 'numeric_code' => '232', 'capital' => 'Asmara', 'flag_emoji' => '🇪🇷', 'is_active' => true],
            ['name' => 'Estonia', 'code' => 'EE', 'code3' => 'EST', 'numeric_code' => '233', 'capital' => 'Tallinn', 'flag_emoji' => '🇪🇪', 'is_active' => true],
            ['name' => 'Eswatini', 'code' => 'SZ', 'code3' => 'SWZ', 'numeric_code' => '748', 'capital' => 'Mbabane', 'flag_emoji' => '🇸🇿', 'is_active' => true],
            ['name' => 'Ethiopia', 'code' => 'ET', 'code3' => 'ETH', 'numeric_code' => '231', 'capital' => 'Addis Ababa', 'flag_emoji' => '🇪🇹', 'is_active' => true],
            ['name' => 'Fiji', 'code' => 'FJ', 'code3' => 'FJI', 'numeric_code' => '242', 'capital' => 'Suva', 'flag_emoji' => '🇫🇯', 'is_active' => true],
            ['name' => 'Finland', 'code' => 'FI', 'code3' => 'FIN', 'numeric_code' => '246', 'capital' => 'Helsinki', 'flag_emoji' => '🇫🇮', 'is_active' => true],
            ['name' => 'France', 'code' => 'FR', 'code3' => 'FRA', 'numeric_code' => '250', 'capital' => 'Paris', 'flag_emoji' => '🇫🇷', 'is_active' => true],
            ['name' => 'Gabon', 'code' => 'GA', 'code3' => 'GAB', 'numeric_code' => '266', 'capital' => 'Libreville', 'flag_emoji' => '🇬🇦', 'is_active' => true],
            ['name' => 'Gambia', 'code' => 'GM', 'code3' => 'GMB', 'numeric_code' => '270', 'capital' => 'Banjul', 'flag_emoji' => '🇬🇲', 'is_active' => true],
            ['name' => 'Georgia', 'code' => 'GE', 'code3' => 'GEO', 'numeric_code' => '268', 'capital' => 'Tbilisi', 'flag_emoji' => '🇬🇪', 'is_active' => true],
            ['name' => 'Germany', 'code' => 'DE', 'code3' => 'DEU', 'numeric_code' => '276', 'capital' => 'Berlin', 'flag_emoji' => '🇩🇪', 'is_active' => true],
            ['name' => 'Ghana', 'code' => 'GH', 'code3' => 'GHA', 'numeric_code' => '288', 'capital' => 'Accra', 'flag_emoji' => '🇬🇭', 'is_active' => true],
            ['name' => 'Greece', 'code' => 'GR', 'code3' => 'GRC', 'numeric_code' => '300', 'capital' => 'Athens', 'flag_emoji' => '🇬🇷', 'is_active' => true],
            ['name' => 'Grenada', 'code' => 'GD', 'code3' => 'GRD', 'numeric_code' => '308', 'capital' => "St. George's", 'flag_emoji' => '🇬🇩', 'is_active' => true],
            ['name' => 'Guatemala', 'code' => 'GT', 'code3' => 'GTM', 'numeric_code' => '320', 'capital' => 'Guatemala City', 'flag_emoji' => '🇬🇹', 'is_active' => true],
            ['name' => 'Guinea', 'code' => 'GN', 'code3' => 'GIN', 'numeric_code' => '324', 'capital' => 'Conakry', 'flag_emoji' => '🇬🇳', 'is_active' => true],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'code3' => 'GNB', 'numeric_code' => '624', 'capital' => 'Bissau', 'flag_emoji' => '🇬🇼', 'is_active' => true],
            ['name' => 'Guyana', 'code' => 'GY', 'code3' => 'GUY', 'numeric_code' => '328', 'capital' => 'Georgetown', 'flag_emoji' => '🇬🇾', 'is_active' => true],
            ['name' => 'Haiti', 'code' => 'HT', 'code3' => 'HTI', 'numeric_code' => '332', 'capital' => 'Port-au-Prince', 'flag_emoji' => '🇭🇹', 'is_active' => true],
            ['name' => 'Holy See', 'code' => 'VA', 'code3' => 'VAT', 'numeric_code' => '336', 'capital' => 'Vatican City', 'flag_emoji' => '🇻🇦', 'is_active' => true],
            ['name' => 'Honduras', 'code' => 'HN', 'code3' => 'HND', 'numeric_code' => '340', 'capital' => 'Tegucigalpa', 'flag_emoji' => '🇭🇳', 'is_active' => true],
            ['name' => 'Hong Kong', 'code' => 'HK', 'code3' => 'HKG', 'numeric_code' => '344', 'capital' => 'Hong Kong', 'flag_emoji' => '🇭🇰', 'is_active' => true],
            ['name' => 'Hungary', 'code' => 'HU', 'code3' => 'HUN', 'numeric_code' => '348', 'capital' => 'Budapest', 'flag_emoji' => '🇭🇺', 'is_active' => true],
            ['name' => 'Iceland', 'code' => 'IS', 'code3' => 'ISL', 'numeric_code' => '352', 'capital' => 'Reykjavik', 'flag_emoji' => '🇮🇸', 'is_active' => true],
            ['name' => 'India', 'code' => 'IN', 'code3' => 'IND', 'numeric_code' => '356', 'capital' => 'New Delhi', 'flag_emoji' => '🇮🇳', 'is_active' => true],
            ['name' => 'Indonesia', 'code' => 'ID', 'code3' => 'IDN', 'numeric_code' => '360', 'capital' => 'Jakarta', 'flag_emoji' => '🇮🇩', 'is_active' => true],
            ['name' => 'Iran', 'code' => 'IR', 'code3' => 'IRN', 'numeric_code' => '364', 'capital' => 'Tehran', 'flag_emoji' => '🇮🇷', 'is_active' => true],
            ['name' => 'Iraq', 'code' => 'IQ', 'code3' => 'IRQ', 'numeric_code' => '368', 'capital' => 'Baghdad', 'flag_emoji' => '🇮🇶', 'is_active' => true],
            ['name' => 'Ireland', 'code' => 'IE', 'code3' => 'IRL', 'numeric_code' => '372', 'capital' => 'Dublin', 'flag_emoji' => '🇮🇪', 'is_active' => true],
            ['name' => 'Israel', 'code' => 'IL', 'code3' => 'ISR', 'numeric_code' => '376', 'capital' => 'Jerusalem', 'flag_emoji' => '🇮🇱', 'is_active' => true],
            ['name' => 'Italy', 'code' => 'IT', 'code3' => 'ITA', 'numeric_code' => '380', 'capital' => 'Rome', 'flag_emoji' => '🇮🇹', 'is_active' => true],
            ['name' => 'Jamaica', 'code' => 'JM', 'code3' => 'JAM', 'numeric_code' => '388', 'capital' => 'Kingston', 'flag_emoji' => '🇯🇲', 'is_active' => true],
            ['name' => 'Japan', 'code' => 'JP', 'code3' => 'JPN', 'numeric_code' => '392', 'capital' => 'Tokyo', 'flag_emoji' => '🇯🇵', 'is_active' => true],
            ['name' => 'Jordan', 'code' => 'JO', 'code3' => 'JOR', 'numeric_code' => '400', 'capital' => 'Amman', 'flag_emoji' => '🇯🇴', 'is_active' => true],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'code3' => 'KAZ', 'numeric_code' => '398', 'capital' => 'Astana', 'flag_emoji' => '🇰🇿', 'is_active' => true],
            ['name' => 'Kenya', 'code' => 'KE', 'code3' => 'KEN', 'numeric_code' => '404', 'capital' => 'Nairobi', 'flag_emoji' => '🇰🇪', 'is_active' => true],
            ['name' => 'Kiribati', 'code' => 'KI', 'code3' => 'KIR', 'numeric_code' => '296', 'capital' => 'Tarawa', 'flag_emoji' => '🇰🇮', 'is_active' => true],
            ['name' => 'Kuwait', 'code' => 'KW', 'code3' => 'KWT', 'numeric_code' => '414', 'capital' => 'Kuwait City', 'flag_emoji' => '🇰🇼', 'is_active' => true],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'code3' => 'KGZ', 'numeric_code' => '417', 'capital' => 'Bishkek', 'flag_emoji' => '🇰🇬', 'is_active' => true],
            ['name' => 'Laos', 'code' => 'LA', 'code3' => 'LAO', 'numeric_code' => '418', 'capital' => 'Vientiane', 'flag_emoji' => '🇱🇦', 'is_active' => true],
            ['name' => 'Latvia', 'code' => 'LV', 'code3' => 'LVA', 'numeric_code' => '428', 'capital' => 'Riga', 'flag_emoji' => '🇱🇻', 'is_active' => true],
            ['name' => 'Lebanon', 'code' => 'LB', 'code3' => 'LBN', 'numeric_code' => '422', 'capital' => 'Beirut', 'flag_emoji' => '🇱🇧', 'is_active' => true],
            ['name' => 'Lesotho', 'code' => 'LS', 'code3' => 'LSO', 'numeric_code' => '426', 'capital' => 'Maseru', 'flag_emoji' => '🇱🇸', 'is_active' => true],
            ['name' => 'Liberia', 'code' => 'LR', 'code3' => 'LBR', 'numeric_code' => '430', 'capital' => 'Monrovia', 'flag_emoji' => '🇱🇷', 'is_active' => true],
            ['name' => 'Libya', 'code' => 'LY', 'code3' => 'LBY', 'numeric_code' => '434', 'capital' => 'Tripoli', 'flag_emoji' => '🇱🇾', 'is_active' => true],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'code3' => 'LIE', 'numeric_code' => '438', 'capital' => 'Vaduz', 'flag_emoji' => '🇱🇮', 'is_active' => true],
            ['name' => 'Lithuania', 'code' => 'LT', 'code3' => 'LTU', 'numeric_code' => '440', 'capital' => 'Vilnius', 'flag_emoji' => '🇱🇹', 'is_active' => true],
            ['name' => 'Luxembourg', 'code' => 'LU', 'code3' => 'LUX', 'numeric_code' => '442', 'capital' => 'Luxembourg', 'flag_emoji' => '🇱🇺', 'is_active' => true],
            ['name' => 'Madagascar', 'code' => 'MG', 'code3' => 'MDG', 'numeric_code' => '450', 'capital' => 'Antananarivo', 'flag_emoji' => '🇲🇬', 'is_active' => true],
            ['name' => 'Malawi', 'code' => 'MW', 'code3' => 'MWI', 'numeric_code' => '454', 'capital' => 'Lilongwe', 'flag_emoji' => '🇲🇼', 'is_active' => true],
            ['name' => 'Malaysia', 'code' => 'MY', 'code3' => 'MYS', 'numeric_code' => '458', 'capital' => 'Kuala Lumpur', 'flag_emoji' => '🇲🇾', 'is_active' => true],
            ['name' => 'Maldives', 'code' => 'MV', 'code3' => 'MDV', 'numeric_code' => '462', 'capital' => 'Malé', 'flag_emoji' => '🇲🇻', 'is_active' => true],
            ['name' => 'Mali', 'code' => 'ML', 'code3' => 'MLI', 'numeric_code' => '466', 'capital' => 'Bamako', 'flag_emoji' => '🇲🇱', 'is_active' => true],
            ['name' => 'Malta', 'code' => 'MT', 'code3' => 'MLT', 'numeric_code' => '470', 'capital' => 'Valletta', 'flag_emoji' => '🇲🇹', 'is_active' => true],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'code3' => 'MHL', 'numeric_code' => '584', 'capital' => 'Majuro', 'flag_emoji' => '🇲🇭', 'is_active' => true],
            ['name' => 'Mauritania', 'code' => 'MR', 'code3' => 'MRT', 'numeric_code' => '478', 'capital' => 'Nouakchott', 'flag_emoji' => '🇲🇷', 'is_active' => true],
            ['name' => 'Mauritius', 'code' => 'MU', 'code3' => 'MUS', 'numeric_code' => '480', 'capital' => 'Port Louis', 'flag_emoji' => '🇲🇺', 'is_active' => true],
            ['name' => 'Mexico', 'code' => 'MX', 'code3' => 'MEX', 'numeric_code' => '484', 'capital' => 'Mexico City', 'flag_emoji' => '🇲🇽', 'is_active' => true],
            ['name' => 'Micronesia', 'code' => 'FM', 'code3' => 'FSM', 'numeric_code' => '583', 'capital' => 'Palikir', 'flag_emoji' => '🇫🇲', 'is_active' => true],
            ['name' => 'Moldova', 'code' => 'MD', 'code3' => 'MDA', 'numeric_code' => '498', 'capital' => 'Chișinău', 'flag_emoji' => '🇲🇩', 'is_active' => true],
            ['name' => 'Monaco', 'code' => 'MC', 'code3' => 'MCO', 'numeric_code' => '492', 'capital' => 'Monaco', 'flag_emoji' => '🇲🇨', 'is_active' => true],
            ['name' => 'Mongolia', 'code' => 'MN', 'code3' => 'MNG', 'numeric_code' => '496', 'capital' => 'Ulaanbaatar', 'flag_emoji' => '🇲🇳', 'is_active' => true],
            ['name' => 'Montenegro', 'code' => 'ME', 'code3' => 'MNE', 'numeric_code' => '499', 'capital' => 'Podgorica', 'flag_emoji' => '🇲🇪', 'is_active' => true],
            ['name' => 'Morocco', 'code' => 'MA', 'code3' => 'MAR', 'numeric_code' => '504', 'capital' => 'Rabat', 'flag_emoji' => '🇲🇦', 'is_active' => true],
            ['name' => 'Mozambique', 'code' => 'MZ', 'code3' => 'MOZ', 'numeric_code' => '508', 'capital' => 'Maputo', 'flag_emoji' => '🇲🇿', 'is_active' => true],
            ['name' => 'Myanmar', 'code' => 'MM', 'code3' => 'MMR', 'numeric_code' => '104', 'capital' => 'Naypyidaw', 'flag_emoji' => '🇲🇲', 'is_active' => true],
            ['name' => 'Namibia', 'code' => 'NA', 'code3' => 'NAM', 'numeric_code' => '516', 'capital' => 'Windhoek', 'flag_emoji' => '🇳🇦', 'is_active' => true],
            ['name' => 'Nauru', 'code' => 'NR', 'code3' => 'NRU', 'numeric_code' => '520', 'capital' => 'Yaren', 'flag_emoji' => '🇳🇷', 'is_active' => true],
            ['name' => 'Nepal', 'code' => 'NP', 'code3' => 'NPL', 'numeric_code' => '524', 'capital' => 'Kathmandu', 'flag_emoji' => '🇳🇵', 'is_active' => true],
            ['name' => 'Netherlands', 'code' => 'NL', 'code3' => 'NLD', 'numeric_code' => '528', 'capital' => 'Amsterdam', 'flag_emoji' => '🇳🇱', 'is_active' => true],
            ['name' => 'New Zealand', 'code' => 'NZ', 'code3' => 'NZL', 'numeric_code' => '554', 'capital' => 'Wellington', 'flag_emoji' => '🇳🇿', 'is_active' => true],
            ['name' => 'Nicaragua', 'code' => 'NI', 'code3' => 'NIC', 'numeric_code' => '558', 'capital' => 'Managua', 'flag_emoji' => '🇳🇮', 'is_active' => true],
            ['name' => 'Niger', 'code' => 'NE', 'code3' => 'NER', 'numeric_code' => '562', 'capital' => 'Niamey', 'flag_emoji' => '🇳🇪', 'is_active' => true],
            ['name' => 'Nigeria', 'code' => 'NG', 'code3' => 'NGA', 'numeric_code' => '566', 'capital' => 'Abuja', 'flag_emoji' => '🇳🇬', 'is_active' => true],
            ['name' => 'North Korea', 'code' => 'KP', 'code3' => 'PRK', 'numeric_code' => '408', 'capital' => 'Pyongyang', 'flag_emoji' => '🇰🇵', 'is_active' => true],
            ['name' => 'North Macedonia', 'code' => 'MK', 'code3' => 'MKD', 'numeric_code' => '807', 'capital' => 'Skopje', 'flag_emoji' => '🇲🇰', 'is_active' => true],
            ['name' => 'Norway', 'code' => 'NO', 'code3' => 'NOR', 'numeric_code' => '578', 'capital' => 'Oslo', 'flag_emoji' => '🇳🇴', 'is_active' => true],
            ['name' => 'Oman', 'code' => 'OM', 'code3' => 'OMN', 'numeric_code' => '512', 'capital' => 'Muscat', 'flag_emoji' => '🇴🇲', 'is_active' => true],
            ['name' => 'Pakistan', 'code' => 'PK', 'code3' => 'PAK', 'numeric_code' => '586', 'capital' => 'Islamabad', 'flag_emoji' => '🇵🇰', 'is_active' => true],
            ['name' => 'Palau', 'code' => 'PW', 'code3' => 'PLW', 'numeric_code' => '585', 'capital' => 'Ngerulmud', 'flag_emoji' => '🇵🇼', 'is_active' => true],
            ['name' => 'Palestine', 'code' => 'PS', 'code3' => 'PSE', 'numeric_code' => '275', 'capital' => 'Ramallah', 'flag_emoji' => '🇵🇸', 'is_active' => true],
            ['name' => 'Panama', 'code' => 'PA', 'code3' => 'PAN', 'numeric_code' => '591', 'capital' => 'Panama City', 'flag_emoji' => '🇵🇦', 'is_active' => true],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'code3' => 'PNG', 'numeric_code' => '598', 'capital' => 'Port Moresby', 'flag_emoji' => '🇵🇬', 'is_active' => true],
            ['name' => 'Paraguay', 'code' => 'PY', 'code3' => 'PRY', 'numeric_code' => '600', 'capital' => 'Asunción', 'flag_emoji' => '🇵🇾', 'is_active' => true],
            ['name' => 'Peru', 'code' => 'PE', 'code3' => 'PER', 'numeric_code' => '604', 'capital' => 'Lima', 'flag_emoji' => '🇵🇪', 'is_active' => true],
            ['name' => 'Philippines', 'code' => 'PH', 'code3' => 'PHL', 'numeric_code' => '608', 'capital' => 'Manila', 'flag_emoji' => '🇵🇭', 'is_active' => true],
            ['name' => 'Poland', 'code' => 'PL', 'code3' => 'POL', 'numeric_code' => '616', 'capital' => 'Warsaw', 'flag_emoji' => '🇵🇱', 'is_active' => true],
            ['name' => 'Portugal', 'code' => 'PT', 'code3' => 'PRT', 'numeric_code' => '620', 'capital' => 'Lisbon', 'flag_emoji' => '🇵🇹', 'is_active' => true],
            ['name' => 'Qatar', 'code' => 'QA', 'code3' => 'QAT', 'numeric_code' => '634', 'capital' => 'Doha', 'flag_emoji' => '🇶🇦', 'is_active' => true],
            ['name' => 'Romania', 'code' => 'RO', 'code3' => 'ROU', 'numeric_code' => '642', 'capital' => 'Bucharest', 'flag_emoji' => '🇷🇴', 'is_active' => true],
            ['name' => 'Russia', 'code' => 'RU', 'code3' => 'RUS', 'numeric_code' => '643', 'capital' => 'Moscow', 'flag_emoji' => '🇷🇺', 'is_active' => true],
            ['name' => 'Rwanda', 'code' => 'RW', 'code3' => 'RWA', 'numeric_code' => '646', 'capital' => 'Kigali', 'flag_emoji' => '🇷🇼', 'is_active' => true],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'code3' => 'KNA', 'numeric_code' => '659', 'capital' => 'Basseterre', 'flag_emoji' => '🇰🇳', 'is_active' => true],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'code3' => 'LCA', 'numeric_code' => '662', 'capital' => 'Castries', 'flag_emoji' => '🇱🇨', 'is_active' => true],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'code3' => 'VCT', 'numeric_code' => '670', 'capital' => 'Kingstown', 'flag_emoji' => '🇻🇨', 'is_active' => true],
            ['name' => 'Samoa', 'code' => 'WS', 'code3' => 'WSM', 'numeric_code' => '882', 'capital' => 'Apia', 'flag_emoji' => '🇼🇸', 'is_active' => true],
            ['name' => 'San Marino', 'code' => 'SM', 'code3' => 'SMR', 'numeric_code' => '674', 'capital' => 'San Marino', 'flag_emoji' => '🇸🇲', 'is_active' => true],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'code3' => 'STP', 'numeric_code' => '678', 'capital' => 'São Tomé', 'flag_emoji' => '🇸🇹', 'is_active' => true],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'code3' => 'SAU', 'numeric_code' => '682', 'capital' => 'Riyadh', 'flag_emoji' => '🇸🇦', 'is_active' => true],
            ['name' => 'Senegal', 'code' => 'SN', 'code3' => 'SEN', 'numeric_code' => '686', 'capital' => 'Dakar', 'flag_emoji' => '🇸🇳', 'is_active' => true],
            ['name' => 'Serbia', 'code' => 'RS', 'code3' => 'SRB', 'numeric_code' => '688', 'capital' => 'Belgrade', 'flag_emoji' => '🇷🇸', 'is_active' => true],
            ['name' => 'Seychelles', 'code' => 'SC', 'code3' => 'SYC', 'numeric_code' => '690', 'capital' => 'Victoria', 'flag_emoji' => '🇸🇨', 'is_active' => true],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'code3' => 'SLE', 'numeric_code' => '694', 'capital' => 'Freetown', 'flag_emoji' => '🇸🇱', 'is_active' => true],
            ['name' => 'Singapore', 'code' => 'SG', 'code3' => 'SGP', 'numeric_code' => '702', 'capital' => 'Singapore', 'flag_emoji' => '🇸🇬', 'is_active' => true],
            ['name' => 'Slovakia', 'code' => 'SK', 'code3' => 'SVK', 'numeric_code' => '703', 'capital' => 'Bratislava', 'flag_emoji' => '🇸🇰', 'is_active' => true],
            ['name' => 'Slovenia', 'code' => 'SI', 'code3' => 'SVN', 'numeric_code' => '705', 'capital' => 'Ljubljana', 'flag_emoji' => '🇸🇮', 'is_active' => true],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'code3' => 'SLB', 'numeric_code' => '090', 'capital' => 'Honiara', 'flag_emoji' => '🇸🇧', 'is_active' => true],
            ['name' => 'Somalia', 'code' => 'SO', 'code3' => 'SOM', 'numeric_code' => '706', 'capital' => 'Mogadishu', 'flag_emoji' => '🇸🇴', 'is_active' => true],
            ['name' => 'South Africa', 'code' => 'ZA', 'code3' => 'ZAF', 'numeric_code' => '710', 'capital' => 'Pretoria', 'flag_emoji' => '🇿🇦', 'is_active' => true],
            ['name' => 'South Korea', 'code' => 'KR', 'code3' => 'KOR', 'numeric_code' => '410', 'capital' => 'Seoul', 'flag_emoji' => '🇰🇷', 'is_active' => true],
            ['name' => 'South Sudan', 'code' => 'SS', 'code3' => 'SSD', 'numeric_code' => '728', 'capital' => 'Juba', 'flag_emoji' => '🇸🇸', 'is_active' => true],
            ['name' => 'Spain', 'code' => 'ES', 'code3' => 'ESP', 'numeric_code' => '724', 'capital' => 'Madrid', 'flag_emoji' => '🇪🇸', 'is_active' => true],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'code3' => 'LKA', 'numeric_code' => '144', 'capital' => 'Colombo', 'flag_emoji' => '🇱🇰', 'is_active' => true],
            ['name' => 'Sudan', 'code' => 'SD', 'code3' => 'SDN', 'numeric_code' => '729', 'capital' => 'Khartoum', 'flag_emoji' => '🇸🇩', 'is_active' => true],
            ['name' => 'Suriname', 'code' => 'SR', 'code3' => 'SUR', 'numeric_code' => '740', 'capital' => 'Paramaribo', 'flag_emoji' => '🇸🇷', 'is_active' => true],
            ['name' => 'Sweden', 'code' => 'SE', 'code3' => 'SWE', 'numeric_code' => '752', 'capital' => 'Stockholm', 'flag_emoji' => '🇸🇪', 'is_active' => true],
            ['name' => 'Switzerland', 'code' => 'CH', 'code3' => 'CHE', 'numeric_code' => '756', 'capital' => 'Bern', 'flag_emoji' => '🇨🇭', 'is_active' => true],
            ['name' => 'Syria', 'code' => 'SY', 'code3' => 'SYR', 'numeric_code' => '760', 'capital' => 'Damascus', 'flag_emoji' => '🇸🇾', 'is_active' => true],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'code3' => 'TJK', 'numeric_code' => '762', 'capital' => 'Dushanbe', 'flag_emoji' => '🇹🇯', 'is_active' => true],
            ['name' => 'Tanzania', 'code' => 'TZ', 'code3' => 'TZA', 'numeric_code' => '834', 'capital' => 'Dodoma', 'flag_emoji' => '🇹🇿', 'is_active' => true],
            ['name' => 'Thailand', 'code' => 'TH', 'code3' => 'THA', 'numeric_code' => '764', 'capital' => 'Bangkok', 'flag_emoji' => '🇹🇭', 'is_active' => true],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'code3' => 'TLS', 'numeric_code' => '626', 'capital' => 'Dili', 'flag_emoji' => '🇹🇱', 'is_active' => true],
            ['name' => 'Togo', 'code' => 'TG', 'code3' => 'TGO', 'numeric_code' => '768', 'capital' => 'Lomé', 'flag_emoji' => '🇹🇬', 'is_active' => true],
            ['name' => 'Tonga', 'code' => 'TO', 'code3' => 'TON', 'numeric_code' => '776', 'capital' => "Nuku'alofa", 'flag_emoji' => '🇹🇴', 'is_active' => true],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'code3' => 'TTO', 'numeric_code' => '780', 'capital' => 'Port of Spain', 'flag_emoji' => '🇹🇹', 'is_active' => true],
            ['name' => 'Tunisia', 'code' => 'TN', 'code3' => 'TUN', 'numeric_code' => '788', 'capital' => 'Tunis', 'flag_emoji' => '🇹🇳', 'is_active' => true],
            ['name' => 'Turkey', 'code' => 'TR', 'code3' => 'TUR', 'numeric_code' => '792', 'capital' => 'Ankara', 'flag_emoji' => '🇹🇷', 'is_active' => true],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'code3' => 'TKM', 'numeric_code' => '795', 'capital' => 'Ashgabat', 'flag_emoji' => '🇹🇲', 'is_active' => true],
            ['name' => 'Tuvalu', 'code' => 'TV', 'code3' => 'TUV', 'numeric_code' => '798', 'capital' => 'Funafuti', 'flag_emoji' => '🇹🇻', 'is_active' => true],
            ['name' => 'Uganda', 'code' => 'UG', 'code3' => 'UGA', 'numeric_code' => '800', 'capital' => 'Kampala', 'flag_emoji' => '🇺🇬', 'is_active' => true],
            ['name' => 'Ukraine', 'code' => 'UA', 'code3' => 'UKR', 'numeric_code' => '804', 'capital' => 'Kyiv', 'flag_emoji' => '🇺🇦', 'is_active' => true],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'code3' => 'ARE', 'numeric_code' => '784', 'capital' => 'Abu Dhabi', 'flag_emoji' => '🇦🇪', 'is_active' => true],
            ['name' => 'United Kingdom', 'code' => 'GB', 'code3' => 'GBR', 'numeric_code' => '826', 'capital' => 'London', 'flag_emoji' => '🇬🇧', 'is_active' => true],
            ['name' => 'United States', 'code' => 'US', 'code3' => 'USA', 'numeric_code' => '840', 'capital' => 'Washington, D.C.', 'flag_emoji' => '🇺🇸', 'is_active' => true],
            ['name' => 'Uruguay', 'code' => 'UY', 'code3' => 'URY', 'numeric_code' => '858', 'capital' => 'Montevideo', 'flag_emoji' => '🇺🇾', 'is_active' => true],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'code3' => 'UZB', 'numeric_code' => '860', 'capital' => 'Tashkent', 'flag_emoji' => '🇺🇿', 'is_active' => true],
            ['name' => 'Vanuatu', 'code' => 'VU', 'code3' => 'VUT', 'numeric_code' => '548', 'capital' => 'Port Vila', 'flag_emoji' => '🇻🇺', 'is_active' => true],
            ['name' => 'Venezuela', 'code' => 'VE', 'code3' => 'VEN', 'numeric_code' => '862', 'capital' => 'Caracas', 'flag_emoji' => '🇻🇪', 'is_active' => true],
            ['name' => 'Vietnam', 'code' => 'VN', 'code3' => 'VNM', 'numeric_code' => '704', 'capital' => 'Hanoi', 'flag_emoji' => '🇻🇳', 'is_active' => true],
            ['name' => 'Yemen', 'code' => 'YE', 'code3' => 'YEM', 'numeric_code' => '887', 'capital' => 'Sana’a', 'flag_emoji' => '🇾🇪', 'is_active' => true],
            ['name' => 'Zambia', 'code' => 'ZM', 'code3' => 'ZMB', 'numeric_code' => '894', 'capital' => 'Lusaka', 'flag_emoji' => '🇿🇲', 'is_active' => true],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'code3' => 'ZWE', 'numeric_code' => '716', 'capital' => 'Harare', 'flag_emoji' => '🇿🇼', 'is_active' => true],
        ];

        DB::table('countries')->insert($countries);
    }
}
